export const USER_PUBLIC_SELECT = {
  id: true,
  email: true,
  name: true,
  lastname: true,
  cedula: true,
  direction: true,
  status: true,
  emailVerified: true,
  senescytCode: true,
  professionalStatus: true,
  signatureCertFingerprint: true,
  signatureCertCommonName: true,
  signatureCertNationalId: true,
  signatureCertIssuerCn: true,
  signatureCertValidFrom: true,
  signatureCertValidTo: true,
  signatureProfileCapturedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;
